### ISSUE TITLE
No module named quickstartup.settings_utils

### ISSUE THREAD

**Issue by darrindickey** [osantana/quickstartup-template#5]
I ran `./manage.py migrate`. I get the following error: 
Traceback (most recent call last):
  File "./manage.py", line 8, in <module>
    from quickstartup.settings_utils import get_project_package
ImportError: No module named quickstartup.settings_utils

Did I miss a step?

**Comment by georgeyk** [comment]
Hi @darrindickey 

Can you check if "quickstartup" package was installed ? (```pip install -r requirements-local.txt``` should have installed it)
The module is there:
https://github.com/osantana/quickstartup/blob/0.9.5/quickstartup/settings_utils.py

**Comment by darrindickey** [comment]
It did. It's one of the first things I checked and I ran it a second time to be sure.

**Comment by georgeyk** [comment]
@darrindickey that's odd.

I did a installation here and got some issues with the steps to configure the ".env" file (sqlite db path), then migrate command executed without errors.

Check it out: https://gist.github.com/georgeyk/22c447902fc764568cc62704ccf35482

There are some issues related to the folder structure, imho, but it runs.

**Comment by darrindickey** [comment]
@georgeyk Perfect. I don't know what I was doing, but I followed along with what you did and it appears to have installed properly. Thank you!!

**Comment by georgeyk** [comment]
@darrindickey I'll close this issue, ok ? o/
